# Converts a set of edges generated by `showg -e` to the dotfile format

import fileinput

graph_open = False
graph_line = 0

for line in fileinput.input():
    if graph_open:
        if graph_line == 0:
            graph_line = int(line.split()[1])
        else:
            for l in line.split("  "):
                print("  {} -- {}".format(*l.strip("\n").split()))
                graph_line -= 1

            if graph_line == 0:
                graph_open = False
                print("}")

    elif line.startswith("Graph"):
        graph_open = True
        print(line.split(", ")[0] + " {")
